### ISSUE TITLE
Using Capella elements in VE documents as cross reference

### ISSUE THREAD

**Issue by dsryzhov** [labs4capella/mms-capella#11]
Hi,

Unable to use Capella elements for crossreferencing in VE documents.

It's not possible find Capella element for cross-reference by it's name\description.
But it's possible to find element for cross-reference by it's Metatype and ID. 
In later case name\description of the found element is empty and can't be used.

Model elements exported to MMS from Capella does not have name and description attributes.
Capella names and description are exported to 
EMF_FEATURE__name and EMF_FEATURE__description attributes.

See for example test element from my test export.
https://mms.openmbee.org/alfresco/service/projects/PROJECT-7b851ff4-4512-4a0b-840a-9022cff764bc-CapellaMMSProject/refs/master/elements/dce7dcf5-f672-4cc0-a381-c00118bbc263

Element that can be cross-referenced should contain name\description attributes
https://mms.openmbee.org/alfresco/service/projects/PROJECT-d94630c2-576c-4edd-a8cd-ae3ecd25d16c/refs/master/elements/_hidden_MMS_1517947271625_b16400f2-2031-4754-b23e-5d720535cd8b_pei

to open this links use login\password openmbeeguest\guest

Am I right that current implementation does not help to use Capella elements as a cross references in VE documents?
Is there a plan to make it possible

Regards,
Dmitry

**Comment by j-barata** [comment]
Hello Dmitry,

The main use case for this connector was the integration with MMS.
We didn't considered yet the integration with Visual Editor.

I've seen the document links that you've sent and I have some remarks :
- The "name" attribute could be added, indeed
- As for the element's description attribute, the sent exemple contains a "documentation" attribute (and not "description") : which one shall be chosen ?
- the prefix "EMF_FEATURE__" is used in order to facilitate the retrieval of an EMF model from MMS data, but this could be adapted
- Some elements in Capella doesn't have a name attribute (e.g. the relationships are actual elements which have an id but doesn't have a name), how will VE manage those elements ?

**Comment by dsryzhov** [comment]
Thanks for your quick response!

* you are right, documentation (not description) attribute should be used for VE integration. 
* many Capella relationships have names (they are subclasses of NamedElement). Some relationships does not have names (allocation, realization and so on). I think if we want to cross reference these elements in VE via their names than name attribute should be added to MMS for this elemens (for example generated from Source and Target element names). These elements do have description in Capella model. So they can be referenced by MMS documentation attribute.

To be able to edit model elements via VE documents name\documentation attributes should not be dublicated.
I mean information should be only in name\documentation attributes and EMF_FEATURE__name and EMF_FEATURE__description attributes should be deleted.

Currently this attributes are not the only problem with VE integration.
When documents\view are created in VE new version of model is created.
When trying to checkout commit with new model version to Capella 
the following error occurs (there is no such problem when I checkout initial commit that doens not contains VE documents)

com.thalesgroup.mde.openmbee.connector.mms.sirius.ui
Error
Tue Nov 03 09:46:54 MSK 2020
Unexpected exception while trying to import project 'PROJECT-7b851ff4-4512-4a0b-840a-9022cff764bc-CapellaMMSProject' from MMS 'https://mms.openmbee.org/alfresco/service' under organization '7b851ff4-4512-4a0b-840a-9022cff764bc'

java.lang.NullPointerException
	at com.thalesgroup.mde.openmbee.connector.mms.sirius.EmfMmsModelElementDescriptorConverter.fromMMS(EmfMmsModelElementDescriptorConverter.java:83)
	at com.thalesgroup.mde.openmbee.connector.mms.sirius.SiriusProjectConnector.fromMms(SiriusProjectConnector.java:218)
	at com.thalesgroup.mde.openmbee.connector.mms.sirius.ui.ImportRunnable.executeImport(ImportRunnable.java:91)
	at com.thalesgroup.mde.openmbee.connector.mms.sirius.ui.ImportRunnable.run(ImportRunnable.java:54)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by j-barata** [comment]
Ok, thanks for the update.

Could you, please, open a separate issue for the NPE issue ?

Thanks

**Comment by dsryzhov** [comment]
Have created separate NPE issue 
https://github.com/labs4capella/mms-capella/issues/12
